import Head from 'next/head'
import { Footer, Header, Link } from '../components';
import styles from '../styles/Home.module.css'
import { FC, useEffect } from 'react';
import gsap from 'gsap';
import ScrollTrigger from 'gsap/ScrollTrigger';

// gsap.registerPlugin(ScrollTrigger);

const person = {
  firstName: 'Hicham',
  lastName: 'El assari',
  jobTitle: 'Frontend ',
  skills: 'React and React native (expo cli)',
  email: 'elassari19@gmail.com',
  articles: <Link href={'/articles'} title='Articles' />,
  portfolio: <Link href={'/project'} title='project' />,
}

const Home: FC = () => {

  // gsap.registerPlugin()

  useEffect(() => {
    gsap.from('#title, #desc',1,{dispaly: 'none', x: '1000px', duration: 1, delay: .5, ease: 'back.out(.8)', stagger: .4})
  }, [])

  return (
    <div className={styles.container} >
      <Head>
        <title>Portfolio</title>
        <meta name="description" content="Generated by hicham el assari" />
      </Head>

      <Header />

      <main className={styles.main} style={{color: '#fff'}}>

        <div className={styles.title} style={{maxWidth: 700}} id='title'>
          <h1 className={styles.title}>
          Frontend web developer {person.portfolio}
          </h1>

          <h4 style={{fontSize: 22, fontWeight: '500'}}>
            React.JS, React Native (expo cli), Redux, Typescript, GSAP, and Node.JS. Check out my latest web software development {person.portfolio} projects.
          </h4>
        </div>

       <div className={styles.description} id='desc'>
         <p className={styles.pargraph}>
            Hello, my name is {person.firstName} {person.lastName}. 
            I am an award-winning {person.jobTitle}web 
            developer and UI/UX javascript specialist. Check out 
            my {person.articles}, {person.skills} 
            UI components at the code laboratory. Feel free to take a look at my 
            latest projects on the web {person.portfolio} page. 
            contact me on @mail {person.email}
         </p>
       </div>

      </main>

      <Footer />

    </div>
  )
}

export default Home
